### ISSUE TITLE
Using :format and overriding render causes issues

### ISSUE THREAD

**Issue by plukevdh** [lotus/view#39]
New user here, eager to contribute if I can.

For reference: I'm running on the master branches of most of the parts of Lotus:

```ruby
gem 'lotusrb', github: "lotus/lotus"
gem 'lotus-controller', github: "lotus/controller"
gem 'lotus-view', github: "lotus/view"
gem 'lotus-model', github: "lotus/model"
```

I have a few that I initially wrote like so:

```ruby
module Measurements
  module Views
    class Index
      include Lotus::View

      format :json

      def render
        measurements.to_json
      end
    end
  end
end
```

Which errors with the following:

```
NoMethodError: undefined method `new' for nil:NilClass
	/Users/plukevdh/src/Personal/rpeat_server/.bundle/gems/ruby/2.1.0/bundler/gems/view-7b7a1b3118a1/lib/lotus/view/rendering/registry.rb:93:in `resolve'
	/Users/plukevdh/src/Personal/rpeat_server/.bundle/gems/ruby/2.1.0/bundler/gems/view-7b7a1b3118a1/lib/lotus/view/rendering.rb:236:in `render'
	/Users/plukevdh/src/Personal/rpeat_server/.bundle/gems/ruby/2.1.0/bundler/gems/lotus-134cc1e82d85/lib/lotus/rendering_policy.rb:34:in `render'
	/Users/plukevdh/src/Personal/rpeat_server/.bundle/gems/ruby/2.1.0/bundler/gems/lotus-134cc1e82d85/lib/lotus/application.rb:156:in `block in call'
	/Users/plukevdh/src/Personal/rpeat_server/.bundle/gems/ruby/2.1.0/bundler/gems/lotus-134cc1e82d85/lib/lotus/application.rb:155:in `tap'
	/Users/plukevdh/src/Personal/rpeat_server/.bundle/gems/ruby/2.1.0/bundler/gems/lotus-134cc1e82d85/lib/lotus/application.rb:155:in `call'
```

If I remove the `format: :json`, it works as expected (with the output of the overridden render method being rendered) but it took me some time to get there. However, this is somewhat confusing behavior. Is this an issue that could be solved by better docs or by more clear errors perhaps? Overall, it makes sense once you think about it (setting explicit format but running arbitrary code in the `render` method), but it'd be nice if it was clearer.

**Comment by jodosha** [comment]
Closing this for because it became stale.
